sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - main # build master branch only
before_install:
  - cd Blog
  - ls -al
  - npm install hexo-cli -g
nstall:
  - npm install
script:
  - hexo clean
  - hexo generate
 
deploy:
  type: git
  repo: https://github.com/thread-liu/thread-liu.github.io
  branch: master

after_success:
  - git config --global user.name "thread-liu"
  - git config --global user.email "lk9608@outlook.com"
  - sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
  - hexo deploy
