sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - main # build master branch only
before_install:
  - cd Blog
  - ls -al
  - npm install hexo-cli -g
script:
  - hexo clean
  - hexo generate
deploy:
  type: git
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  repo: https://github.com/thread-liu/thread-liu.github.io
  on:
    all_branches: true # solve a permission problem
    branch: master
