sudo: false

language: node_js

notifications:
  email: false
  
node_js:
- 10

cache: npm

branches:
  only:
  - main
  
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
- git config --global user.name "thread-liu"
- git config --global user.email "lk9608@outlook.com"

install:
- cd Blog  
- npm install hexo-cli -g
- npm install hexo-deployer-git --save
- npm install

script:
- hexo clean
- hexo generate

after_success:
- hexo deploy
